# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/zynq_axi_smc_1_0.xci
# IP: The module: 'zynq_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/bd_f516.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_5/bd_f516_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_9/bd_f516_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_10/bd_f516_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_6/bd_f516_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_7/bd_f516_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_8/bd_f516_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_2/bd_f516_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_3/bd_f516_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_4/bd_f516_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_0/bd_f516_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_5/bd_f516_s00a2s_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_9/bd_f516_m00s2a_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_6/bd_f516_sawn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_7/bd_f516_swn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_8/bd_f516_sbn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/zynq_axi_smc_1_0.xci
# IP: The module: 'zynq_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/bd_f516.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_5/bd_f516_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_9/bd_f516_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_10/bd_f516_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_6/bd_f516_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_7/bd_f516_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_8/bd_f516_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_2/bd_f516_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_3/bd_f516_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_4/bd_f516_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_0/bd_f516_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_5/bd_f516_s00a2s_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_9/bd_f516_m00s2a_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_6/bd_f516_sawn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_7/bd_f516_swn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_8/bd_f516_sbn_0_ooc.xdc

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
