# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0.xci
# IP: The module: 'zynq_axis_data_fifo_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axis_data_fifo_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axis_data_fifo_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0.xci
# IP: The module: 'zynq_axis_data_fifo_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axis_data_fifo_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axis_data_fifo_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
