# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kenan/Documents/two_fifo/two_fifo/two_fifo.cache/wt [current_project]
set_property parent.project_path /home/kenan/Documents/two_fifo/two_fifo/two_fifo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo /home/kenan/Documents/two_fifo/two_fifo/two_fifo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/hdl/zynq_wrapper.v
add_files /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/zynq.bd
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_dma_0_0/zynq_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_dma_0_0/zynq_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_dma_0_0/zynq_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_0/zynq_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_0/zynq_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_0/zynq_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_5/bd_7cab_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_8/bd_7cab_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_6/bd_7cab_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_7/bd_7cab_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_1/bd_7cab_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/bd_0/ip/ip_1/bd_7cab_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_5/bd_f516_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_9/bd_f516_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_6/bd_f516_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_7/bd_f516_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_8/bd_f516_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/bd_0/ip/ip_1/bd_f516_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_0_0/zynq_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_0_0/zynq_axis_data_fifo_0_0/zynq_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0/zynq_axis_data_fifo_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kenan/Documents/two_fifo/two_fifo/two_fifo.srcs/sources_1/bd/zynq/zynq_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zynq_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zynq_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zynq_wrapper_utilization_synth.rpt -pb zynq_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
